version: '3'

services:
  remote_pc:
    # run the robot ros core as well as a headless gazebo simulation
    image: brean/ros2-turtlebot3-remote-pc:humble
    tty: True
    container_name: ros2-turtlebot3-remote-pc-humble
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        ROS_DISTRO: humble
    environment: 
      - DISPLAY
      - "ROS_DISTRO=humble"
      - NVIDIA_VISIBLE_DEVICES=all # for docker-nvidia2
      - NVIDIA_DRIVER_CAPABILITIES=all # for docker-nvidia2
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    privileged: true  # for gazebo gui
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro  # for gazebo gui
      - ./map:/map:z  # to save the map
    networks:
      - turtlebot
    # command: ["ros2", "launch", "turtlebot3_cartographer", "cartographer.launch.py"]

networks:
  turtlebot:
    external: true
